#====================================================
# spring boot配置
#
# 完整文档：
#====================================================

spring:
  profiles:
    # 测试dev
    active: dev
    # 生产prod
#    active: prod
  application:
    name: member

# 日志配置dev
logback-logstash-tcp: localhost:9700
logback-application-path: applicationLog/
logback-performance-path: performanceLog/
logback-max-history: 30