#====================================================
# 正式环境配置
#
# 完整文档：
#====================================================

#====================================================
# 测试环境配置
#
# 完整文档：
#====================================================

spring:
    #数据库
#    datasource:
#        name: mysql
#        url: jdbc:mysql://127.0.0.1:3306/commerce?useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: sql123
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
# rabbitmq
#  rabbitmq:
#    host: 47.98.37.120
#    port: 5672
#    username: rabbit
#    password: 13cast
#    publisher-confirms: true
#    virtual-host: /
  # 默认时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    inetutils:
      default-ip-address: 127.0.0.1

server:
  port: 10002
  tomcat:
    uri-encoding: utf-8

# 微服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:root@127.0.0.1:10000/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${spring.cloud.inetutils.default-ip-address}
    ip-address: ${spring.cloud.inetutils.default-ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.inetutils.default-ip-address}:${server.port}

# 停止服务
endpoints:
  shutdown:
    #开启shutdown端点
    enabled: true
    path: stop
management:
  security:
    #是否启用安全
    enabled: true
  port: 10002
  address: 127.0.0.1

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.member.model.po
  #开启驼峰命名转换
  configuration:
      map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#swagger
swagger2:
    package: com.member.controller

#es
#elasticsearch:
#  ip: 127.0.0.1
#  port: 9300
#  pool: 5
#  cluster-name: es

druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        name: mysql
        url: jdbc:mysql://127.0.0.1:3306/commerce?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: sql123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    slave:
        name: mysql
        url: jdbc:mysql://127.0.0.1:3306/commerce?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: sql123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#redis
redis:
    ADDR: 127.0.0.1
    AUTH: redisl1
    PORT: 6379
    MAXACTIVE: -1
    MAXIDLE: 200
    MAXWAIT: 500
    TIMEOUT: 500
    TESTON_BORROW: true

# token域
EXTERNAL_APEX: localhost

# 熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE