#====================================================
# spring boot配置
#
# 完整文档：
#====================================================

spring:
  profiles:
    # 测试dev 生产prod
    active: dev
#    active: prod
  application:
    name: member

